force-app/main/default/objects/Departure_Date__c/Departure_Date__c.object-meta.xml
<CustomObject>
    <label>Departure Date</label>
    <nameField>
        <label>Departure Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departure Date</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Departure_Date__c/fields/Single_Occupancy__c.field-meta.xml
<CustomField>
    <fullName>Single_Occupancy__c</fullName>
    <label>Single Occupancy</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Departure_Date__c/fields/Trip_Option__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option__c</fullName>
    <label>Trip Option</label>
    <referenceTo>Trip_Option__c</referenceTo>
    <relationshipLabel>Departure Date</relationshipLabel>
    <relationshipName>Departure_Date</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Option__c/Trip_Option__c.object-meta.xml
<CustomObject>
    <label>Trip Option</label>
    <nameField>
        <label>Trip Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Option__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Options</relationshipLabel>
    <relationshipName>Trip_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/aus_GetPriceApi.cls
@RestResource(urlMapping='/getPrice')
global with sharing class aus_GetPriceApi {
  global class mainWrapper{
       	global String price{get;set;}
      global String singleoccupancyPrice{get;set;}
      
    }
    global class mainWrapperReturn{
    	 global String tripOption{get;set;}
         global String trip{get;set;}
        global String departureDate{get;set;}
    }
       
    @HttpPost
    global static mainWrapper orderSearch(){
        
        RestRequest req = RestContext.request;
        String requestBodyString = req.requestBody.tostring();        
        mainWrapperReturn mainWrap = (mainWrapperReturn)JSON.deserialize(requestBodyString, mainWrapperReturn.class);
        Trip_Option__c result =  [Select Id, Name,Price__c from Trip_Option__c where Name =: mainWrap.tripOption And  Trip__r.Name=: mainWrap.trip ];
        Departure_Date__c depDate =  [Select Id, Name,Price__c,Single_Occupancy__c from Departure_Date__c where Name =: mainWrap.departureDate And  Trip_Option__c=: result.Id ];
        mainWrapper mainwrap1 =new mainWrapper();
        mainwrap1.price=string.valueOf(depDate.Price__c);
          mainwrap1.singleoccupancyPrice=string.valueOf(depDate.Single_Occupancy__c);

        system.debug('result'+depDate.Price__c);
        return mainwrap1;
    } 

}