force-app/main/default/objects/Cancellation_Refund__c/Cancellation_Refund__c.object-meta.xml
<CustomObject>
    <label>Cancellation</label>
    <nameField>
        <displayFormat>CAN-{0000}</displayFormat>
        <label>Cancellation Refund Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cancellation Refunds</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Cancellation_Refund__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <label>Orders</label>
    <referenceTo>Orders__c</referenceTo>
    <relationshipLabel>Cancellation</relationshipLabel>
    <relationshipName>Cancellation_Refunds</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Coupons__c/fields/Cancellation_Refund__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation Refund</label>
    <referenceTo>Cancellation_Refund__c</referenceTo>
    <relationshipLabel>Coupons</relationshipLabel>
    <relationshipName>Coupons</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Departure_Date__c/Departure_Date__c.object-meta.xml
<CustomObject>
    <label>Departure Date</label>
    <nameField>
        <label>Departure Date Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Departure Date</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Departure_Date__c/fields/Trip_Option__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option__c</fullName>
    <label>Trip Option</label>
    <referenceTo>Trip_Option__c</referenceTo>
    <relationshipLabel>Departure Date</relationshipLabel>
    <relationshipName>Departure_Date</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Line_Items__c/Order_Line_Items__c.object-meta.xml
<CustomObject>
    <label>Order Line Item</label>
    <nameField>
        <displayFormat>OLI-{0000}</displayFormat>
        <label>Order Line Items Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Order Line Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Line_Items__c/fields/Cancellation_Refund__c.field-meta.xml
<CustomField>
    <fullName>Cancellation_Refund__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cancellation Refund</label>
    <referenceTo>Cancellation_Refund__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Items__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Date</label>
    <referenceTo>Departure_Date__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Items__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Orders__c</referenceTo>
    <relationshipLabel>Order Line Items</relationshipLabel>
    <relationshipName>Order_Line_Items</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Line_Items__c/fields/Refund_Reason_c__c.field-meta.xml
<CustomField>
    <fullName>Refund_Reason_c__c</fullName>
    <label>Refund_Reason__c</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Customer - Unable to travel - Medical</fullName>
            </value>
            <value>
                <fullName>Customer - Unable to Travel - Death</fullName>
            </value>
            <value>
                <fullName>Customer - Unable to Travel - Change of Mind</fullName>
            </value>
            <value>
                <fullName>Customer - Unable to Travel - Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Internal - Offload</fullName>
            </value>
            <value>
                <fullName>Internal - Merchant</fullName>
            </value>
            <value>
                <fullName>Internal - Partner/ 3rd Party</fullName>
            </value>
            <value>
                <fullName>Internal - System Error</fullName>
            </value>
            <value>
                <fullName>Internal - Staff Error</fullName>
            </value>
            <value>
                <fullName>Internal - Goodwill</fullName>
            </value>
            <value>
                <fullName>Internal - Customer Complaint</fullName>
            </value>
            <value>
                <fullName>Internal - Min Numbers not met</fullName>
            </value>
            <value>
                <fullName>External - Merchant</fullName>
            </value>
            <value>
                <fullName>External - Force Majeure</fullName>
            </value>
            <value>
                <fullName>External - Partner/ 3rd Party</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Orders__c/Orders__c.object-meta.xml
<CustomObject>
    <label>Orders</label>
    <nameField>
        <displayFormat>Order-{0000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Orders__c/fields/Departure_Date__c.field-meta.xml
<CustomField>
    <fullName>Departure_Date__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Departure Date</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Departure_Date__c.Trip_Option__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trip_Option__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Departure_Date__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orderss</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Orders__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipName>Order</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Orders__c/fields/Trip_Option__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option__c</fullName>
    <label>Trip Option</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Trip_Option__c.Trip__c</field>
            <operation>equals</operation>
            <valueField>$Source.Trip__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Trip_Option__c</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Order</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Orders__c/recordTypes/Self_Guided.recordType-meta.xml
<RecordType>
    <fullName>Self_Guided</fullName>
    <active>true</active>
    <label>Self Guided</label>
</RecordType>

force-app/main/default/objects/Passenger__c/Passenger__c.object-meta.xml
<CustomObject>
    <label>Passenger</label>
    <nameField>
        <label>First Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Passenger</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Passenger__c/fields/Order_Line_Items__c.field-meta.xml
<CustomField>
    <fullName>Order_Line_Items__c</fullName>
    <label>Order Line Items</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Orders__c</field>
            <operation>equals</operation>
            <valueField>Order_Line_Items__c.Orders__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Order_Line_Items__c</referenceTo>
    <relationshipLabel>Passenger</relationshipLabel>
    <relationshipName>Passenger</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Passenger__c/fields/Orders__c.field-meta.xml
<CustomField>
    <fullName>Orders__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orders</label>
    <referenceTo>Orders__c</referenceTo>
    <relationshipLabel>Passenger</relationshipLabel>
    <relationshipName>Passengers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/recordTypes/self_guided.recordType-meta.xml
<RecordType>
    <fullName>self_guided</fullName>
    <active>true</active>
    <label>Self Guided</label>
</RecordType>

force-app/main/default/objects/Trip_Option__c/Trip_Option__c.object-meta.xml
<CustomObject>
    <label>Trip Option</label>
    <nameField>
        <label>Trip Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Option__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Options</relationshipLabel>
    <relationshipName>Trip_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/recordTypes/Self_Guided.recordType-meta.xml
<RecordType>
    <fullName>Self_Guided</fullName>
    <active>true</active>
    <label>Self Guided</label>
</RecordType>

force-app/main/default/classes/orderCancellationFormControllerTest.cls
@isTest
public class orderCancellationFormControllerTest {
@isTest
    public static void tesMethod1Insert(){
        
       
        
        //create trip 
           Trip__c trip = TestDataFactoryApexClass.createTrip('self_guided');
           insert trip;
       
        
        //create trip option
        Trip_Option__c tripOption = TestDataFactoryApexClass.createTripOption(trip.Id, 'Self_Guided');
        insert tripOption;
        
        
        //create departure date
        Departure_Date__c DepartureDate = TestDataFactoryApexClass.createDepartureDate(tripOption.id,'Rejected','Full Credit;Full Refund');
        insert DepartureDate;
        //system.debug('DepartureDate: '+DepartureDate.id);
        
        Orders__c order = TestDataFactoryApexClass.createOrder('Self_Guided', trip.id, tripOption.id, DepartureDate.id,'Cancelled');
        insert order;
        //system.debug('order: '+order.id);
        
        //create Order_Line_Items__c
        Order_Line_Items__c orderLineItems = TestDataFactoryApexClass.createorderLineItems(order.id,DepartureDate.Id,'Internal - Offload','CS Rejected');
        insert orderLineItems;
        //system.debug('orderLineItems: '+orderLineItems.id);
        
        
        //create Passenger
        Passenger__c Passenger = TestDataFactoryApexClass.createPassenger(orderLineItems.id, order.id);
        insert Passenger;
        
        String recId=order.id;
		orderCancellationFormController.minNotMetCheckData min=orderCancellationFormController.verifyMinNotMetApprovalStatus(order.id);
        List<orderCancellationFormController.recordDataWrapper> lst=orderCancellationFormController.fetchReordDataApexApproval(order.id);
        
       List<orderCancellationFormController.ApprovalHistoryWrapper> lst1=orderCancellationFormController.fetchReordDataApexApprovalHistory(order.id);
       List<orderCancellationFormController.recordDataWrapper> recData=orderCancellationFormController.fetchReordDataApex(order.id, 'Order');
        List<String> Str=orderCancellationFormController.getPicklistvalues('Order_Line_Items__c','Refund_Reason_c__c');
       orderCancellationFormController.saveAndCancel(order.id, recData, true);
       orderCancellationFormController.cancelCompleteOrder(order.id,recData);
       orderCancellationFormController.submitForApproval(recId, recData, true, true);
       orderCancellationFormController.submitForApproval(recId, recData, true, true);
        orderCancellationFormController.sendForApprovalPostDocumentation(recId, recData, true);
        
      Cancellation_Refund__c cn=new Cancellation_Refund__c();
       cn=orderCancellationFormController.canRefRecordAssignment(recId,true);
        
        Coupons__c cpn=new Coupons__c(Send_Coupon__c=true,Cancellation_Refund__c=cn.Id);
        insert cpn;
        orderCancellationFormController.settingSendCouponTrue(cn.Id);
    }
    @isTest
    public static void tesMethod2Insert(){
        
       
        
        //create trip 
           Trip__c trip = TestDataFactoryApexClass.createTrip('self_guided');
           insert trip;
       
        
        //create trip option
        Trip_Option__c tripOption = TestDataFactoryApexClass.createTripOption(trip.Id, 'Self_Guided');
        insert tripOption;
        
        
        //create departure date
        Departure_Date__c DepartureDate = TestDataFactoryApexClass.createDepartureDate(tripOption.id,'processed','Full Credit;Full Refund');
        insert DepartureDate;
        //system.debug('DepartureDate: '+DepartureDate.id);
        
        Orders__c order = TestDataFactoryApexClass.createOrder('Self_Guided', trip.id, tripOption.id, DepartureDate.id,'Secured');
        insert order;
        //system.debug('order: '+order.id);
        
        //create Order_Line_Items__c
        Order_Line_Items__c orderLineItems = TestDataFactoryApexClass.createorderLineItems(order.id,DepartureDate.Id,'Internal - Min Numbers not met','CS Rejected');
        insert orderLineItems;
        //system.debug('orderLineItems: '+orderLineItems.id);
        
        
        //create Passenger
        Passenger__c Passenger = TestDataFactoryApexClass.createPassenger(orderLineItems.id, order.id);
        insert Passenger;
        
        
		orderCancellationFormController.minNotMetCheckData min=orderCancellationFormController.verifyMinNotMetApprovalStatus(order.id);
        
        
       
        
   
    }
}