force-app/main/default/objects/Itinerary__c/Itinerary__c.object-meta.xml
<CustomObject>
    <label>Itinerary</label>
    <nameField>
        <label>Itinerary Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itineraries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Itinerary__c/fields/Itinerary_Overview__c.field-meta.xml
<CustomField>
    <fullName>Itinerary_Overview__c</fullName>
    <label>Itinerary Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Meal__c.field-meta.xml
<CustomField>
    <fullName>Meal__c</fullName>
    <label>Meal</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Breakfast</fullName>
            </value>
            <value>
                <fullName>Lunch</fullName>
            </value>
            <value>
                <fullName>Dinner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Meal_Information__c.field-meta.xml
<CustomField>
    <fullName>Meal_Information__c</fullName>
    <label>Meal Information</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Meal_Requirement__c.field-meta.xml
<CustomField>
    <fullName>Meal_Requirement__c</fullName>
    <label>Meal Requirement</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Veg</fullName>
            </value>
            <value>
                <fullName>No-Veg</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Title__c.field-meta.xml
<CustomField>
    <fullName>Title__c</fullName>
    <label>Title</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Trip_Option__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option__c</fullName>
    <label>Trip Option</label>
    <referenceTo>Trip_Option__c</referenceTo>
    <relationshipLabel>itineraries</relationshipLabel>
    <relationshipName>itineraries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Itinerary__c/fields/Walking_Info__c.field-meta.xml
<CustomField>
    <fullName>Walking_Info__c</fullName>
    <label>Walking Info</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Meal__c/Meal__c.object-meta.xml
<CustomObject>
    <label>Meal</label>
    <nameField>
        <label>Meals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Meals</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/Trip__c.object-meta.xml
<CustomObject>
    <label>Trip</label>
    <nameField>
        <label>Trip Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip__c/fields/Start_Location__c.field-meta.xml
<CustomField>
    <fullName>Start_Location__c</fullName>
    <label>Start Location</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/Trip_Option__c.object-meta.xml
<CustomObject>
    <label>Trip Option</label>
    <nameField>
        <label>Trip Option Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trip Options</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Trip_Option__c/fields/Alternative_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Alternative_Start_Date__c</fullName>
    <label>Alternative Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/End_Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>End_Day_of_Week__c</fullName>
    <label>End Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Number_of_days__c.field-meta.xml
<CustomField>
    <fullName>Number_of_days__c</fullName>
    <label>Number of days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Single_Occupancy_Charge__c.field-meta.xml
<CustomField>
    <fullName>Single_Occupancy_Charge__c</fullName>
    <label>Single Occupancy Charge</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Start_Day_of_Week__c.field-meta.xml
<CustomField>
    <fullName>Start_Day_of_Week__c</fullName>
    <label>Start Day of Week</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Tuesday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Thursday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
            <value>
                <fullName>Saturday</fullName>
            </value>
            <value>
                <fullName>Sunday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Start_Location__c.field-meta.xml
<CustomField>
    <fullName>Start_Location__c</fullName>
    <label>Start Location</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>Queensland</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
            <value>
                <fullName>Tasmania</fullName>
            </value>
            <value>
                <fullName>Western Australia</fullName>
            </value>
            <value>
                <fullName>Northern Territory</fullName>
            </value>
            <value>
                <fullName>Victoria</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Read to Export</fullName>
            </value>
            <value>
                <fullName>Submit for Approval</fullName>
            </value>
            <value>
                <fullName>Ready to be published on website</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Total_Walk_Distance__c.field-meta.xml
<CustomField>
    <fullName>Total_Walk_Distance__c</fullName>
    <label>Total Walk/Distance</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Trip__c.field-meta.xml
<CustomField>
    <fullName>Trip__c</fullName>
    <label>Trip</label>
    <referenceTo>Trip__c</referenceTo>
    <relationshipLabel>Trip Options</relationshipLabel>
    <relationshipName>Trip_Options</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Trip_Option_External_ID__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option_External_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Trip Option External ID</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Trip_Option_Highlights__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option_Highlights__c</fullName>
    <label>Trip Option Highlights</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Trip_Option_Overview__c.field-meta.xml
<CustomField>
    <fullName>Trip_Option_Overview__c</fullName>
    <label>Trip Option Overview</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Trip_Type__c.field-meta.xml
<CustomField>
    <fullName>Trip_Type__c</fullName>
    <label>Trip Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Self-Guided</fullName>
            </value>
            <value>
                <fullName>Group Guided</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trip_Option__c/fields/Walk_Grade__c.field-meta.xml
<CustomField>
    <fullName>Walk_Grade__c</fullName>
    <label>Walk Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy to Moderate</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Moderate to Challenging</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Auswalk_tripcloneApexHandler.cls
public class Auswalk_tripcloneApexHandler {

    public class tripOptionData {
        @auraenabled public string tripOptionName{get;set;}
		@auraenabled public string tripTypeName{get;set;}
        @auraenabled public double tripPrice{get;set;}
        @auraenabled public date dateFrom{get;set;}
        @auraenabled public date dateTo{get;set;}
        @auraenabled public boolean showitinerary {get;set;}
        @auraenabled public List<itineraryData> Itinerary{get;set;}

    }
    
    public class cloneData{
        @auraenabled public string optionName{get;set;}
        @auraenabled public string optionType{get;set;}
        @auraenabled public string optionPrice{get;set;}
        @auraenabled public string optionNewName{get;set;}
    }
    
    public class itineraryData {
        @auraenabled public string itineraryName{get;set;}

    }
    @auraenabled
    public static List<tripOptionData> getTripOptionData(string tripId){

        system.debug('tripId >'+tripId);
     List<Trip_Option__c> tripOption = [SELECT Id,name,Trip_Type__c,Price__c,Start_Date__c,End_Date__c,(Select id,name,Day__c FROM itineraries__r) FROM Trip_Option__c WHERE trip__c=:tripId];
     system.debug('tripOption :'+tripOption);

     List<Itinerary__c> itiList = [Select id,name, Day__c,Trip_Option__r.trip__c FROM Itinerary__c where Trip_Option__r.trip__c =:tripId Order By Day__c ASC];        
        
     List<tripOptionData> triptionList = new List<tripOptionData>();

        for(Trip_Option__c option:tripOption){
            tripOptionData optionData = new tripOptionData();
			List<itineraryData> itiData = new List<itineraryData>();
            
            optionData.tripOptionName=option.Name;
            optionData.tripTypeName=option.Trip_Type__c;
            optionData.tripPrice=option.Price__c;
            optionData.dateFrom=option.Start_Date__c;
            optionData.dateTo=option.End_Date__c;
            
            if(!itiList.isEmpty()){
                for(Itinerary__c varIti:itiList){
                    itineraryData iti = new itineraryData();
            		iti.itineraryName='Day '+varIti.Day__c;
                    itiData.add(iti);
                }
            }
            if(itiData!=null){
                optionData.showitinerary=true;
                optionData.Itinerary=itiData;
            }
            triptionList.add(optionData);
        }
        //system.debug('triptionList '+triptionList);
      Return triptionList;
        
}
    //clone record
    @auraenabled
    public static void cloneTripOption(List<cloneData> cloneDataList){
        
        system.debug('insert option Line 67 '+cloneDataList);

        Map<string,string> tripOptionNameMap = new Map<string,string>();
        
        for(cloneData data:cloneDataList){
			tripOptionNameMap.put(data.optionName, data.optionNewName);
        }
        
        system.debug('tripOptionNameMap Line 75==> '+tripOptionNameMap);
        
        
        List<Trip_Option__c> tripOptionListToClone = new List<Trip_Option__c>();
        List<Itinerary__c> itiListToClone = new List<Itinerary__c>();
        
        List<Trip_Option__c> tripOptionList = [SELECT Id,Name,Trip__c,Trip_Type__c,Alternative_Start_Date__c,Comments__c,Duration__c,End_Date__c,End_Day_of_Week__c,Number_of_days__c,
                                              Price__c,Single_Occupancy_Charge__c,Start_Date__c,Start_Day_of_Week__c,Start_Location__c,Status__c,Total_Walk_Distance__c,Trip_Option_External_ID__c,
                                              Trip_Option_Highlights__c,Trip_Option_Overview__c,Walk_Grade__c FROM Trip_Option__c WHERE name IN:tripOptionNameMap.keySet()];

		system.debug('tripOptionList ==> '+tripOptionList.size());
        
        if(!tripOptionList.isEmpty()){
            for(Trip_Option__c toption : tripOptionList){
                Trip_Option__c option = toption.clone(false,true);
                option.Name=tripOptionNameMap.get(toption.Name);
                option.Trip_Option_External_ID__c='';
                tripOptionListToClone.add(option);
            }
        }
        if(!tripOptionListToClone.isEmpty()){
            insert tripOptionListToClone;
        }
        
        Map<Id,Id> tripOptionIdsMap = new Map<Id,Id>();
        
        List<Trip_Option__c> fetchTripOptionList = [SELECT Id,Name FROM Trip_Option__c WHERE name IN:tripOptionNameMap.values()]; 
        system.debug('fetchTripOptionList Line 100:'+fetchTripOptionList);
        
        
        if(!fetchTripOptionList.isEmpty()){
            
            for(Trip_Option__c newOption:fetchTripOptionList){
                
                for(Trip_Option__c Option:tripOptionList){
                    tripOptionIdsMap.put(Option.id,newOption.id);
                }
            }
        }
        if(!tripOptionIdsMap.isEmpty()){
           system.debug('tripOptionIdsMap Line 113=> '+tripOptionIdsMap);  
            list<Itinerary__c> itiList = [SELECT Id,name,Day__c,Title__c,Trip_Option__c,Walking_Info__c,Itinerary_Overview__c,Meal__c,Meal_Information__c,Meal_Requirement__c,
                                          Status__c From Itinerary__c where Trip_Option__c IN:tripOptionIdsMap.keyset() Order By Day__c ASC];
            
            for(Itinerary__c iti:itiList){ 
                Itinerary__c cloneIti = iti.clone(false,true);
                cloneIti.Trip_Option__c = tripOptionIdsMap.get(iti.Trip_Option__c);
                itiListToClone.add(cloneIti);
            }
        }
        if(!itiListToClone.isEmpty()){
            insert itiListToClone;
            system.debug('itiListToClone Line 125 '+itiListToClone);
        }
   }
}